---
services:
  digstsgql:
    build: .
    command: ["uvicorn", "--factory", "digstsgql.app:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      # Database
      DATABASE__USER: "root"
      DATABASE__PASSWORD: "insecure"
      DATABASE__HOST: "db"
      DATABASE__NAME: "digstsgql"
    volumes:
      # Mount python module to allow live-reload
      - ./digstsgql/:/app/digstsgql/:ro
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "insecure"
      POSTGRES_DB: "digstsgql"
    restart: unless-stopped

  # https://caddyserver.com/docs/running#docker-compose
  caddy:
    profiles: [deploy]
    image: caddy:2
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
